language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

git:
  depth: false

os:
  - linux

services:
  - docker

install: true

jobs:
  include:
    - stage: test 
      script: ./gradlew clean build -x signArchives --no-daemon --console=plain

