language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

git:
  depth: false

os:
  - linux

services:
  - docker

install: true

jobs:
  include:
    - stage: check 
      script: ./gradlew check javadoc

    - stage: test
      script:
        - ./gradlew --no-daemon test

