language: java
jdk:
  - openjdk11
  - oraclejdk11 

git:
  depth: false

os:
  - linux

services:
  - docker

install: true

jobs:
  include:
    - stage: test 
      script: ./gradlew clean build -x signArchives --no-daemon --console=plain

