language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

install:
  - ./gradlew build -x check -x signArchives

jobs:
  include:
    - stage: test
      script: ./gradlew check javadoc

    - env: [ NAME="docker-in-alpine-docker" ]
      script:
        - |
                DOCKER_HOST=unix:///var/run/docker.sock DOCKER_TLS_VERIFY= docker run -t --rm \
                -v "$HOME/.gradle":/root/.gradle/ \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "$(pwd)":"$(pwd)" \
                -w "$(pwd)" \
                openjdk:8-jdk-alpine \
                ./gradlew --no-daemon test

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./gradlew -Pversion=$TRAVIS_TAG release
        on:
          tags: true
          branch: master

