language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

git:
  depth: false

os:
  - linux

services:
  - docker

install: true

jobs:
  include:
    - stage: test 
      script: ./gradlew check --no-daemon
    - script: ./gradlew javadoc --no-daemon
    - script: ./gradlew test --no-daemon

